-- Remove problem statement associations from existing teams to avoid foreign key errors
UPDATE public.teams SET ps_id = NULL;

-- Clear existing dummy problem statements
DELETE FROM public.problem_statements;

-- Insert real SIH 2024 problem statements
INSERT INTO public.problem_statements (ps_code, title, category, domain, organization, description) VALUES
('SIH26001', 'AI-Based early warning and landslide Risk Monitoring System in NER', 'Software', 'Disaster Management', 'Ministry of Development of North Eastern Region (MDoNER)', NULL),
('SIH26002', 'AI-Based Smart Logistics and Accessibility Intelligence Platform for North Eastern Region (NER)', 'Software', 'Smart Automation', 'Ministry of Development of North Eastern Region (MDoNER)', NULL),
('SIH26003', 'AI-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)', 'Software', 'Space Technology', 'Ministry of Development of North Eastern Region (MDoNER)', NULL),
('SIH26004', 'AI-Assisted Early Detection System for Osteoarthritis (OA) Risk Markers in North Eastern Region (NER)', 'Hardware', 'Space Technology', 'Ministry of Development of North Eastern Region (MDoNER)', NULL),
('SIH26005', 'Solar-Powered Smart Mini Cold Storage System for Fresh Vegetables in North Eastern Region (NER)', 'Hardware', 'Smart Vehicles', 'Ministry of Development of North Eastern Region (MDoNER)', NULL),
('SIH26006', 'Development of an Intelligent Freight Forecasting Model for Optimized Vessel Chartering and Bulk Cargo Procurement from overseas to East Coast of India', 'Software', 'Transportation & Logistics', 'Ministry of Steel', NULL),
('SIH26007', 'Safe and Efficient Operation of Mine Vehicles in Fog and Low-Visibility Conditions in Open Cast Iron Ore Mines.', 'Hardware', 'Smart Automation', 'Ministry of Steel', NULL),
('SIH26008', 'Belt Joint Rupture and Conveyor Belt Damages in Iron Ore Mining Industry: Intelligent Monitoring and Prediction of Conveyor Belt Joint Rupture and Damages in Iron Ore Mining Industry.', 'Hardware', 'Smart Automation', 'Ministry of Steel', NULL),
('SIH26009', 'Using AI/ML and Space Technology to Identify Manganese Reserves and Overcome Production Shortfalls.', 'Software', 'Smart Automation', 'Ministry of Steel', NULL),
('SIH26010', 'Survey/Resurvey of Rural Agricultural Land in India', 'Hardware', 'Smart Automation', 'Ministry of Rural Development', NULL),
('SIH26011', '3D ULPIN Generation and Vertical Property Mapping System', 'Software', 'Space Technology', 'Ministry of Rural Development', NULL),
('SIH26012', 'AI-Based Automated Urban Parcel Mapping and Cadastral Feature Extraction System using Drone Imagery', 'Software', 'Robotics and Drones', 'Ministry of Rural Development', NULL),
('SIH26013', 'Automated Integration and Intelligent Harmonization of Multi-source Geospatial Data for Urban Land Record Management.', 'Software', 'Disaster Management', 'Ministry of Rural Development', NULL),
('SIH26014', 'An Integrated GIS-based Digital Public Infrastructure for Land Governance', 'Software', 'Robotics and Drones', 'Ministry of Rural Development', NULL),
('SIH26015', 'Application of Geospatial Techniques for Visualization and Analysis to Interpret Geo-Coded Images to Enhance Watershed Development Outcomes.', 'Software', 'Disaster Management', 'Ministry of Rural Development', NULL),
('SIH26016', 'Real-Time National Land Acquisition & Management System for End-to-End Digital Monitoring and Decision Support', 'Software', 'Miscellaneous', 'Ministry of Rural Development', NULL),
('SIH26017', 'Predictive Analytics System for Early Detection of Land Acquisition Delays', 'Software', 'Agriculture, FoodTech & Rural Development', 'Ministry of Rural Development', NULL),
('SIH26018', 'Intelligent Land Record Digitization and Validation System', 'Software', 'MedTech / BioTech / HealthTech', 'Ministry of Rural Development', NULL),
('SIH26019', 'National Digital Platform for Research, Policy Innovation, and Evidence-Based Land Governance', 'Software', 'Blockchain & Cybersecurity', 'Ministry of Rural Development', NULL),
('SIH26020', 'Design and Development of Innovative Hand-Spinning Equipment for Enhancing Khadi Artisan Productivity and Income', 'Hardware', 'Blockchain & Cybersecurity', 'Ministry of MSME', NULL),
('SIH26021', 'Honey Chain: A blockchain-based system for honey traceability and smart beekeeping management.', 'Software', 'Smart Automation', 'Ministry of MSME', NULL),
('SIH26022', 'Design and develop a smart, solar-powered drying and compact packaging system to support home-based agarbatti manufacturing by rural women artisans.', 'Hardware', 'Agriculture, FoodTech & Rural Development', 'Ministry of MSME', NULL),
('SIH26023', 'AI-Powered Geological, Mining and other Reporting Solution for CMPDI/CIL subsidiaries', 'Software', 'Miscellaneous', 'Ministry of Coal', NULL),
('SIH26024', 'AI-Based Smart Governance and Compliance Monitoring System for Coal Mines', 'Software', 'Smart Automation', 'Ministry of Coal', NULL),
('SIH26025', 'Development of an AI-enabled Low Cost Real Time Mine Subsidence Monitoring, Prediction and Early Warning System for Underground Coal Mines in India', 'Hardware', 'Disaster Management', 'Ministry of Coal', NULL),
('SIH26026', 'Development of Mobile (Quadruped)/Handheld Device/System for Real-Time Detection of Narcotics and Explosives across Indian Railways.', 'Hardware', 'Robotics and Drones', 'Ministry of Railways', NULL),
('SIH26027', 'AI-Powered Automatic Block Planning to Maximize Asset Availability for Train Operations on Indian Railways', 'Software', 'Transportation & Logistics', 'Ministry of Railways', NULL),
('SIH26028', 'Dynamic Forecast of Expected Time of Arrival (ETA) for Coaching Trains', 'Software', 'Disaster Management', 'Ministry of Railways', NULL),
('SIH26029', 'Automated High-Current Short-Circuit Test System for IEC 60898-1:2015 MCB Compliance.', 'Hardware', 'Disaster Management', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26030', 'Automated Cable Specimen Preparation System for IS 10810 and IS 7098 Compliance.', 'Hardware', 'Smart Automation', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26031', 'Quality assessment and grading of onions are often subjective and vary across procurement centers, resulting in disputes and inconsistencies.', 'Software', 'Fitness & Sports', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26032', 'Farmers often face long waiting times, lack of information regarding procurement schedules, and uncertainty about procurement status.', 'Software', 'Heritage & Culture', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26033', 'Multiple intermediaries reduce farmers earnings and increase consumer prices.', 'Software', 'MedTech / BioTech / HealthTech', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26034', 'Software System to check compliance of Packaged Commodities under Legal Metrology (Packaged Commodities) Rules, 2011 by scanning products, images and labels.', 'Software', 'Agriculture, FoodTech & Rural Development', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26035', 'Development of a Software Program/Application for Generation of Test Reports for Non-Automatic Weighing Instruments (NAWI) as per OIML Recommendation R-76', 'Software', 'Smart Vehicles', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26036', 'Development of an Online Verification System for Weighing and Measuring Instruments', 'Software', 'Transportation & Logistics', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26037', 'Adaptive Path Planning and Collision Avoidance for Autonomous Vehicles on Unstructured Indian Roads', 'Software', 'Robotics and Drones', 'MathWorks', NULL),
('SIH26038', 'Explainable AI for Diabetic Retinopathy Screening in Rural India', 'Software', 'Clean & Green Technology', 'MathWorks', NULL),
('SIH26039', 'AI-Powered Underground Mine Safety, Monitoring and Rescue System.', 'Hardware', 'Travel & Tourism', 'Government of Jharkhand', NULL),
('SIH26040', 'Smart Water Purification and Quality Monitoring System for Rural and Mining-Affected Areas.', 'Hardware', 'Renewable / Sustainable Energy', 'Government of Jharkhand', NULL),
('SIH26041', 'AR-Based Vocational Training Simulator for Industrial Safety in Jharkhand''s Mining & Manufacturing Sector', 'Software', 'Blockchain & Cybersecurity', 'Government of Jharkhand', NULL),
('SIH26042', 'AI-Powered Vernacular Pedagogy and Real-Time Translation Tool for Mother Tongue-Based Primary Education', 'Software', 'Smart Education', 'Government of Jharkhand', NULL),
('SIH26043', 'A digital platform to crowdsource societal challenges and facilitate collaborative problem solving through universities and industry partnerships', 'Software', 'Disaster Management', 'Government of Jharkhand', NULL),
('SIH26044', 'Portal for Academia - Industry collaboration for Skill Mapping, Internships and Placement', 'Software', 'Miscellaneous', 'Ministry of Ayush', NULL),
('SIH26045', 'IP-SAKTI Sahayak: a multilingual, RAG-based (source-cited) AI assistant for Intellectual Property and regulatory guidance in Ayurveda, across national and international regimes.', 'Software', 'Toys & Games', 'Ministry of Ayush', NULL),
('SIH26046', 'AIIA Clinical Trials Dashboard - a real-time, cloud-based, GCP-compliant Clinical Trial Management System (CTMS) for Ayurveda research, with CDISC/FHIR-interoperable data, role-based KPIs, and integrated ethics, regulatory (CTRI / NDCT Rules 2019) and pharmacovigilance tracking.', 'Software', 'Space Technology', 'Ministry of Ayush', NULL),
('SIH26047', 'Patient Case-Taking Software', 'Software', 'Smart Automation', 'Ministry of Ayush', NULL),
('SIH26048', 'iKwath - a pod-based smart Kwatha (Kadha) maker that prepares a fresh, AFI/API-standardized decoction from coarse powder (yavakuta churna) on demand, in the shortest practical time without altering the decoction''s quality or yield', 'Hardware', 'Fitness & Sports', 'Ministry of Ayush', NULL),
('SIH26049', 'Modifications to improve the reliability, efficiency, and lifespan of electrical and electronic equipment and systems in the ambient condition of subzero temperature and low pressure of High Altitude Areas (HAA) and Super High Altitude Areas (SHAA) of Ladakh region.', 'Hardware', 'Heritage & Culture', 'DRDO', NULL),
('SIH26050', 'High Altitude Performance Optimization and Robust Design of Anti-Drone System.', 'Hardware', 'MedTech / BioTech / HealthTech', 'DRDO', NULL),
('SIH26051', 'Software Based Model Development for Design of Area Specific Shelter for Thermal Comfort Maintenance.', 'Software', 'Agriculture, FoodTech & Rural Development', 'DRDO', NULL),
('SIH26052', 'To develop an AI/ML-enabled adaptive noise cancellation (ANC) system that effectively suppresses stationary, non-stationary, and impulsive defence noises while maintaining high speech intelligibility and real-time performance on embedded hardware.', 'Hardware', 'Smart Vehicles', 'DRDO', NULL),
('SIH26053', 'Adaptive Variable Resolution 2.5D Lidar Mapping for Dynamic Environment Perception', 'Software', 'Transportation & Logistics', 'DRDO', NULL),
('SIH26054', 'AI-Enabled Real-Time Digital Twin System for Health Monitoring, Fault Prediction and Mission Reliability Enhancement of Aero Piston Engines used in MALE UAVs.', 'Software', 'Robotics and Drones', 'DRDO', NULL),
('SIH26055', 'Smart Scan strategy for Electronic Warfare', 'Software', 'Clean & Green Technology', 'DRDO', NULL),
('SIH26056', 'Development of a Real-time Airfare Price Index for India through Automated Web Scraping of Airline and Online Travel Aggregator Portals for Augmentation of the Consumer Price Index (CPI).', 'Software', 'Travel & Tourism', 'MoSPI', NULL),
('SIH26057', 'AI-Powered Automated Underwater Marine Debris and Anomaly Detection System using Side-Scan Sonar Imagery', 'Software', 'Renewable / Sustainable Energy', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26058', 'Development of a Low-Power, Real-Time Adaptive Software-Defined Sonar Transmitter Payload for Autonomous Underwater Vehicles (AUVs)', 'Hardware', 'Blockchain & Cybersecurity', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26059', 'AI-Enabled Antarctic Sea-Ice, Iceberg Trajectory, and Navigation Decision Support System', 'Software', 'Smart Education', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26060', 'Digital Platform for efficient remote management of Indian Antarctic Research Stations', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26061', 'AI-Driven Smart Energy Management System for Polar Research Stations', 'Software', 'Miscellaneous', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26062', 'Integrated Polar Expedition Logistics and Asset Management System', 'Software', 'Toys & Games', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26063', 'Integrated Polar Science Outreach, Knowledge Repository and Media Dissemination Portal', 'Software', 'Space Technology', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26064', 'Low-Cost Deployable Seafloor Metal Detection Sensor for Ocean Resource Exploration', 'Hardware', 'Smart Resource Conservation', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26065', 'Autonomous Low-Cost Ocean Observation Platform for Polar and Southern Oceans', 'Hardware', 'Smart Automation', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26066', 'OceanEmbed - Satellite Embedding-Based Deep Learning Framework for Reconstruction of Subsurface Ocean Temperature from Surface Satellite Observations.', 'Software', 'Space Technology', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26067', 'Develop a web-based interactive 3D visualization platform that integrates numerical ocean model outputs and in-situ observations.', 'Software', 'Smart Automation', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26068', 'WeatherGPT: Conversational AI for Weather Forecasting, Alerts, and Climate Information', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26069', 'National Weather Big Data Analytics Platform', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26070', 'To develop an Artificial Intelligence (AI) / Machine Learning (ML) based system for identification, classification, and prediction of different tropical cyclone patterns using multi-source satellite data.', 'Software', 'Smart Education', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26071', 'AI/ML-Based Integrated heavy rainfall Early Warning and Inundation Prediction System using Satellite, Radar, observational Weather and numerical weather prediction model data.', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26072', 'AI/ML based Nowcasting of thunderstorm and lightning using atmospheric observation including multiple radars, satellite, lightning and model data.', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26073', 'AI/ML-Based Intelligent Anomaly Detection for Automatic Weather Stations (AWS)', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26074', 'Downscaling of weather forecast from Block level to Panchayat level: Inferring high-resolution plots/data/information from low-resolution plot/data/information/variables for agro-meteorological advisory services.', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26075', 'CAPACITY CONNECT - A Digital Capacity Building and Learning Management Portal to support organizational training, competency development, and knowledge sharing through a centralized web-based platform.', 'Software', 'Smart Education', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26076', 'Development of personalized homepage for ''Mausam'' mobile application', 'Software', 'Miscellaneous', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26077', 'AI-Driven Hyper-Local Early Warning System for Severe Weather Nowcasting', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26078', 'AI-Driven Spatio-Temporal Tracking of Extreme Weather Anomalies in Medium-Range Forecasts', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26079', 'AI-Based Forecast Bust Detection for Medium-Range Weather Forecasts', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26080', 'Regime-Aware AI Post-Processing of Monsoon Rainfall Forecasts', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26081', 'Hybrid AI-NWP Multi-Model Forecast Blending System', 'Software', 'Miscellaneous', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26082', 'Air Pollution-Weather Coupled Forecasting System (Delhi NCR Focus)', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26083', 'Extreme Heatwave Early Warning and Human Thermal Stress Index', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26084', 'Convective scale nowcasting for Thunderstorms, Hail & Cloudbursts (0-6 hr)', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26085', 'Urban Flood Nowcasting System (Drainage and Rainfall Coupling)', 'Software', 'Disaster Management', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26086', 'Hyperlocal Monsoon Onset & Break Prediction System (Block/Village Scale)', 'Software', 'Miscellaneous', 'Ministry of Earth Sciences (MoES)', NULL),
('SIH26087', 'AI-Enabled Cooperative Capacity Building, ERP & Employment Ecosystem', 'Hardware', 'Smart Education', 'Ministry of Cooperation', NULL),
('SIH26088', 'Multilingual Cooperative Governance & Legal Assistance Chatbot', 'Hardware', 'Smart Automation', 'Ministry of Cooperation', NULL),
('SIH26089', 'Cooperative Gig Services Platform for Household & Community Services', 'Software', 'Smart Automation', 'Ministry of Cooperation', NULL),
('SIH26090', 'AI-Driven Market Linkage and Smart Cataloging Mobile Application for Marginalized Artisans', 'Software', 'Miscellaneous', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26091', 'AI-Driven Hyper-Local Business Advisory and Financial Structuring Assistant for Rural Micro-Entrepreneurs', 'Software', 'Miscellaneous', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26092', 'AI-Driven Scheme Matching for Marginalized Entrepreneurs', 'Software', 'Miscellaneous', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26093', 'AI-Based Real-Time Stress and Trauma Assessment Module for Victims/Complainants Accessing NHAA (14566) and Integrated Portal', 'Software', 'Smart Automation', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26094', 'AI-Powered Dynamic Mental Health Monitoring and Distress Prediction System for Victims of Atrocities', 'Software', 'MedTech / BioTech / HealthTech', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26095', 'Smart Real-Time Monitoring & Inspection Mobile App', 'Software', 'Miscellaneous', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26096', 'Digital Heritage Archive for Memorials, Manuscripts & Ambedkar: AI-Powered Institutional Archive and Audio-Visual Knowledge Platform', 'Hardware', 'Heritage & Culture', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26097', 'AI-Driven Voice Assistant for Livelihood Mapping and NSQF-Aligned Skilling Recommendations for SC Communities under GIA component of PM-AJAY', 'Software', 'Smart Education', 'Ministry of Social Justice and Empowerment (MoSJE)', NULL),
('SIH26098', 'Development of a Low-Cost Precision Guidance and Smart Electronic Fuze System for a 155 mm Artillery Shell', 'Hardware', 'Miscellaneous', 'Ministry of Defence (MoD)', NULL),
('SIH26099', 'AI-Driven Standardization and Harmonization of Material Codes Across CPSEs', 'Software', 'Smart Automation', 'Ministry of Petroleum & Natural Gas', NULL),
('SIH26100', 'AI-Powered Integrated Bid Compliance Verification Platform for GeM Procurement', 'Software', 'Smart Automation', 'Ministry of Petroleum & Natural Gas', NULL),
('SIH26101', 'Develop an AI enabled learning platform that identifies competency gaps, recommends personalized training through integration with the iGOT Karmayogi ecosystem, and is capable of generating quizzes and MCQs from uploaded learning materials to strengthen capacity building in India''s Official Statistical System.', 'Software', 'Smart Education', 'MoSPI', NULL),
('SIH26102', 'Development of an AI-powered system to detect anomalies, fraud, and inefficiencies in MPLAD Scheme implementation.', 'Software', 'Miscellaneous', 'MoSPI', NULL),
('SIH26103', 'Use case on web-based integrated project-monitoring platform', 'Software', 'Smart Automation', 'MoSPI', NULL),
('SIH26104', 'AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks', 'Software', 'Miscellaneous', 'All India Council for Technical Education (AICTE)', NULL),
('SIH26105', 'AI-Powered Continuous Cyber Risk Quantification and Investment Optimization Platform', 'Software', 'Blockchain & Cybersecurity', 'All India Council for Technical Education (AICTE)', NULL),
('SIH26106', 'AI-Powered Email Threat Detection, GeoLocation and Forensic Intelligence Platform', 'Software', 'Blockchain & Cybersecurity', 'All India Council for Technical Education (AICTE)', NULL),
('SIH26107', 'AI-powered Intelligent Assistant for Indian Standards and BIS Services for Industries and Consumers', 'Software', 'Smart Automation', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26108', 'AI-Powered Recommendation Engine for Identifying Applicable Indian Standards for Procurement Specifications', 'Software', 'Smart Automation', 'Ministry of Consumer Affairs, Food & Public Distribution', NULL),
('SIH26109', 'AI-Based Predictive Modelling for Early Forecasting of Bovine Mastitis in Indian Dairy Farms', 'Hardware', 'Agriculture, FoodTech & Rural Development', 'Ministry of Fisheries, Animal Husbandry & Dairying', NULL),
('SIH26110', 'Development of a Low-Cost Light-weight Milk Chilling Can for Small-Scale Dairy Farmers', 'Hardware', 'Agriculture, FoodTech & Rural Development', 'Ministry of Fisheries, Animal Husbandry & Dairying', NULL),
('SIH26111', 'Smart AI-Enabled Rapid Feed and Silage Quality Testing System for Dairy Farmers', 'Software', 'Agriculture, FoodTech & Rural Development', 'Ministry of Fisheries, Animal Husbandry & Dairying', NULL),
('SIH26112', 'Design and Develop a Modular Autonomous Mobile Robot (AMR) Platform for Smart Warehouse Automation', 'Hardware', 'Robotics and Drones', 'Autodesk', NULL),
('SIH26113', 'Human augmentation technologies are transforming healthcare, rehabilitation, industrial ergonomics, assistive living, sports, and personal mobility by improving human capabilities and enhancing quality of life.', 'Hardware', 'MedTech / BioTech / HealthTech', 'Autodesk', NULL),
('SIH26114', 'Smart City Site Planning using Autodesk Forma Site Design', 'Software', 'Smart Automation', 'Autodesk', NULL),
('SIH26115', 'Design and Develop a Smart Mobile Medical-Waste Collection and Segregation System', 'Software', 'MedTech / BioTech / HealthTech', 'Autodesk', NULL),
('SIH26116', 'Urban Mixed-Use Design Challenge - Design a centrally located mixed-use building in Autodesk Revit with commercial spaces (Ground + 1st floor) and residential units (up to 8 floors). 1 Level of Basement (Car Parking + EV Charging), Total (B+G+9). Plot size and all required dimensions may be assumed by students (in mm units).', 'Software', 'Smart Education', 'Autodesk', NULL),
('SIH26117', 'Sovereign On-Premise Agentic AI Workbench using Open-Weight Multimodal LLMs for Confidential Industrial Work', 'Software', 'Smart Automation', 'Mangalore Refinery and Petrochemicals Limited (MRPL)', NULL),
('SIH26118', 'Passive Colorimetric H2S Exposure-Dosimeter Wristband with AI-Based Quantitative Reading', 'Hardware', 'Miscellaneous', 'Mangalore Refinery and Petrochemicals Limited (MRPL)', NULL),
('SIH26119', 'Indigenous GPU-Accelerated Optimization Solver (Sovereign Alternative to Express/CPLEX)', 'Software', 'Miscellaneous', 'Mangalore Refinery and Petrochemicals Limited (MRPL)', NULL),
('SIH26120', 'Digital Twin for Well-to-Surface Optimization of Cyclic Steam Stimulation (CSS) and Sucker Rod Pump (SRP) Operations for Heavy Oil Wells of Baghewala Field.', 'Software', 'Smart Automation', 'Oil India Limited', NULL),
('SIH26121', 'eRTMAC-NWIS (Nearby Wells Intelligence System): An AI-Powered Offset Well Knowledge and Decision Support Platform for Drilling Operations', 'Software', 'Smart Automation', 'Oil India Limited', NULL),
('SIH26122', 'Intelligent Data Capture & Schedule-Linking Layer for Infrastructure Project Management: Real-Time Actual Progress Tracking (Planning-to-Execution Bridge)', 'Software', 'Smart Automation', 'Oil India Limited', NULL),
('SIH26123', 'Edge-AI Based Distributed Fleet Coordination for Autonomous Mobile Robots (AMRs) in Smart Warehouses', 'Software', 'Robotics and Drones', 'Bharat Electronics Limited', NULL),
('SIH26124', 'AI-Powered Mobile Urban Intelligence Platform Using Public Transport Fleet', 'Software', 'Fitness & Sports', 'Bharat Electronics Limited', NULL),
('SIH26125', 'Blockchain-Based Secure Platform for Identity, Access Control, and Digital Asset Management', 'Software', 'Blockchain & Cybersecurity', 'Bharat Electronics Limited', NULL),
('SIH26126', 'Vision Based Autonomous Navigation for Unmanned Ground Vehicle for Outdoor Environment', 'Software', 'Robotics and Drones', 'Bharat Electronics Limited', NULL),
('SIH26127', 'City-Wide AI Engine for Multi-Camera ANPR Trajectory Tracking and Urban Traffic Analytics', 'Software', 'Transportation & Logistics', 'Bharat Electronics Limited', NULL),
('SIH26128', 'Efficient systems for early detection, prevention, and management of livestock diseases and animal health issues', 'Software', 'Agriculture, FoodTech & Rural Development', 'Government of Maharashtra', NULL),
('SIH26129', 'System integration and interoperability among government digital platforms, resulting in fragmented service delivery', 'Software', 'Smart Automation', 'Government of Maharashtra', NULL),
('SIH26130', 'Efficiency in streamlining industrial approvals, compliance processes, and access to government support services', 'Software', 'Smart Automation', 'Government of Maharashtra', NULL),
('SIH26131', 'Early detection and management of crop diseases and pest infestations', 'Software', 'Agriculture, FoodTech & Rural Development', 'Government of Maharashtra', NULL),
('SIH26132', 'Strengthening market linkages and price discovery for farmers', 'Software', 'Agriculture, FoodTech & Rural Development', 'Government of Maharashtra', NULL),
('SIH26133', 'Accessibility and quality of public healthcare services, particularly in rural and underserved areas', 'Software', 'MedTech / BioTech / HealthTech', 'Government of Maharashtra', NULL),
('SIH26134', 'Challenges in aligning skill development programs with industry requirements and emerging job market demands', 'Software', 'Miscellaneous', 'Government of Maharashtra', NULL),
('SIH26135', 'Difficulties in tracking employment outcomes, skill gaps, and the impact of skilling initiatives', 'Software', 'Smart Education', 'Government of Maharashtra', NULL),
('SIH26136', 'Startup friendly public procurement mechanism that enables government departments to identify, pilot, procure, and scale innovative solutions from eligible startups', 'Software', 'Smart Automation', 'Government of Maharashtra', NULL),
('SIH26137', 'Quantum-Inspired Intelligent Traffic Route Optimization in Transportation Systems Using Metaheuristic Optimization', 'Software', 'Fitness & Sports', 'Egreen Quanta', NULL),
('SIH26138', 'Quantum-Inspired Fuel Consumption Prediction and Green Fleet Optimization', 'Software', 'Smart Vehicles', 'Egreen Quanta', NULL),
('SIH26139', 'Hybrid Quantum Machine Learning Platform for Early Disease Detection', 'Software', 'MedTech / BioTech / HealthTech', 'Egreen Quanta', NULL),
('SIH26140', 'AI-Based Interactive Quantum Algorithm Learning Platform', 'Software', 'Smart Education', 'Egreen Quanta', NULL),
('SIH26141', 'Quantum-Inspired Cyber Threat Detection for Digital Signature Security', 'Software', 'Blockchain & Cybersecurity', 'Egreen Quanta', NULL),
('SIH26142', 'Deep Learning Based Super Resolution Mapping (SRM) from Medium Resolution Satellite Imageries', 'Software', 'Smart Education', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26143', 'Leveraging satellite imagery to determine oil spills at sea along with AIS data correlations to identify the vessel responsible for the spill.', 'Software', 'Space Technology', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26144', 'Design & Development of a High-Sensitivity Micro Barometer Infrasound Sensor', 'Hardware', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26145', 'AI-Based Detection of Cyber Threats in Unidirectional IP Traffic', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26146', 'AI-Powered Monitoring & Analysis of Bitcoin Transaction Traffic', 'Software', 'Transportation & Logistics', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26147', 'Automated model for analysis of .IQ and .wav files along with signal parameter extraction', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26148', 'Creation of scripts/functions with new programming language to commence Computer & Network forensic analysis without triggering security solutions', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26149', 'Design and Development of an Integrated Secure Data Erasure and Advanced File Recovery Tool for Digital Forensics and Data Sanitization', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26150', 'Development of a Multi-Vendor DVR/NVR Forensic Analysis Tool for Standardized Acquisition, Recovery, and Analysis of Surveillance Evidence.', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26151', 'Dark web threat actor de-anonymization', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26152', 'Social Media Analytics', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26153', 'AI based Network Attack Forecasting from Network Traffic Data', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26154', 'Gen AI Platform for Automated Content Transformation', 'Software', 'Smart Automation', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26155', 'AI-Driven Multi-Vendor Network Security Compliance Auditor', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26156', 'Universal Log Pre-processing Framework', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26157', 'Supervisory Analytics Tool for SOC Assessment (SAT-SA)', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26158', 'Single-Pass Drone Video to Accurate 3D Model Generation System', 'Software', 'Robotics and Drones', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26159', 'SecureMailScope: AI-Assisted Cryptographic Security Posture Assessment for Secure Email Communications', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26160', 'AI-Powered IPsec VPN Protocol Analyzer and Security Assessment Framework', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26161', 'Dam Break Inundation Modelling Using Hydrodynamic Modelling of any River', 'Software', 'Disaster Management', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26162', 'AI-Based Detection and Classification of Industrial Fires and Persistent Thermal Sources Using NASA FIRMS, OSM & Satellite Data', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26163', 'Security Assessment of the World Monitor application', 'Software', 'Miscellaneous', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26164', 'Enterprise Cryptographic Discovery & Analysis Tool (ECDAT)', 'Software', 'Blockchain & Cybersecurity', 'National Technical Research Organisation (NTRO)', NULL),
('SIH26165', 'AI/NLP Engine to Detect Serious Injury & Fatality (SIF) Precursors in OIL''s Unsafe-Act/Unsafe-Condition and Near-Miss Reports', 'Software', 'Miscellaneous', 'Oil India Limited', NULL),
('SIH26166', 'Multi-modal, Sun angle and scale invariant image correspondence using Chandrayaan-2 optical images (OHRC, TMC and IIRS)', 'Software', 'Space Technology', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26167', 'SatQuery AI - An Interactive Vision-Language Assistant for Multimodal Remote Sensing Image Analysis through Text Queries', 'Software', 'Space Technology', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26168', 'AI-ML based Intelligent Dead Reckoning system for seamless navigation', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26169', 'Development of an AI-Based Virtual Camera Tracking System for Coarse Alignment of Mobile Free Space Optical Communication (FSOC) Terminals', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26170', 'AI-Driven Anomaly Detection in Component Burn-In & Screening', 'Software', 'Smart Automation', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26171', 'On-device Visual Perception for Light-weight Browser Agents', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26172', 'Low Latency and Efficient Voice Activator for Edge Devices', 'Hardware', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26173', 'iTantra - Indian Multilingual TTS & STT Aided Neural Transceiver Radio Access for low bitrate links', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26174', 'AI Human Activity Recognition for On-board BAS Experiments', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26175', 'DepthWizard - Single-View Height Estimation and 3D Flythrough', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26176', 'ORCA - Marine Ecosystem Reasoning with Collaborative Agents', 'Software', 'Miscellaneous', 'Indian Space Research Organisation (ISRO)', NULL),
('SIH26177', 'A deployable AI-powered autonomous drone that aids search-and-rescue operations by detecting people and hazards, thereby improving responder safety and reducing victim discovery time.', 'Hardware', 'Robotics and Drones', 'Qualcomm Inc', NULL),
('SIH26178', 'A resilient, AI-powered environmental monitoring network that provides early detection, localized intelligence, and actionable alerts for floods, forest fires, pollution events, and other environmental hazards common in India, enabling authorities and communities to shift from reactive disaster response to proactive risk prevention.', 'Hardware', 'Disaster Management', 'Qualcomm Inc', NULL),
('SIH26179', 'To build an AI-powered retail intelligence platform that delivers real-time shopper analytics, automated inventory visibility, and proactive queue management through on-device AI, enabling retailers to reduce stock-outs, improve customer experience, optimize staffing, and increase operational efficiency while maintaining privacy and minimizing cloud dependency.', 'Hardware', 'Smart Automation', 'Qualcomm Inc', NULL),
('SIH26180', 'A field-deployable AI-powered Smart Farming Assistant that helps farmers detect crop diseases, pests, nutrient deficiencies, and irrigation needs at an early stage, while improving resilience against droughts, floods, heat waves, and other agricultural risks common in India. The solution should enable higher yields, lower input costs, more efficient water usage, and faster response to emerging threats through real-time on-device intelligence.', 'Hardware', 'Disaster Management', 'Qualcomm Inc', NULL),
('SIH26181', 'A secure, AI-powered Personal Health Companion that delivers real-time, privacy-preserving health monitoring and early warning capabilities, helping individuals recognize health risks before they become emergencies. The solution should improve resilience during heat waves, floods, pollution events, and other disasters common in India while enabling continuous health support through on-device intelligence.', 'Hardware', 'MedTech / BioTech / HealthTech', 'Qualcomm Inc', NULL),
('SIH26182', 'Automated Attribution of Unknown Cryptocurrency Wallets to Nearest Virtual Asset Service Providers (VASPs) through Blockchain Intelligence APIs', 'Software', 'Blockchain & Cybersecurity', 'Ministry of Home Affairs', NULL),
('SIH26183', 'Real-Time Identification of Fraud-Linked Cryptocurrency Exchanges from Victim-Reported Suspect Wallet Addresses through Automated Blockchain Analytics', 'Software', 'Blockchain & Cybersecurity', 'Ministry of Home Affairs', NULL),
('SIH26184', 'Development of a Predictive Analytics Framework for Cybercrime Complaints to Forecast Likely Cash Withdrawal Locations in Advance, Enabling Generation of Actionable Intelligence for Timely and Proactive Cybercrime Intervention.', 'Software', 'Blockchain & Cybersecurity', 'Ministry of Home Affairs', NULL),
('SIH26185', 'Helmet mounted conformal antenna for tactical communications in urban CQB environments.', 'Hardware', 'Miscellaneous', 'Ministry of Home Affairs', NULL),
('SIH26186', 'AI-Based Predictive Personnel Stress and Welfare Monitoring System for Uniformed Forces', 'Software', 'MedTech / BioTech / HealthTech', 'Ministry of Home Affairs', NULL),
('SIH26187', 'AI-Based Intelligent Video Analytics Platform for Border Surveillance using existing CCTV Infrastructure.', 'Software', 'Smart Automation', 'Ministry of Home Affairs', NULL),
('SIH26188', 'AI-Based Fake Identity & Document Screening System', 'Software', 'Miscellaneous', 'Ministry of Home Affairs', NULL),
('SIH26189', 'AI-Powered Criminal Network Analysis System', 'Software', 'Blockchain & Cybersecurity', 'Ministry of Home Affairs', NULL),
('SIH26190', 'Secure Digital Document Management System for Legal and Investigation Documents', 'Software', 'Miscellaneous', 'Ministry of Home Affairs', NULL),
('SIH26191', 'Intelligent Identification of Hazard-Based Red Zones, Carrying Capacity Assessment, and Immediate Relocation Needs for Vulnerable Habitations', 'Software', 'Disaster Management', 'Ministry of Home Affairs', NULL),
('SIH26192', 'Flash Flood Prediction System for Hilly Regions using Multi-Source Data', 'Software', 'Disaster Management', 'Ministry of Home Affairs', NULL),
('SIH26193', 'Student Innovation', 'Software', 'Smart Resource Conservation', 'AICTE', NULL),
('SIH26194', 'Student Innovation', 'Software', 'Fitness & Sports', 'AICTE', NULL),
('SIH26195', 'Student Innovation', 'Software', 'Heritage & Culture', 'AICTE', NULL),
('SIH26196', 'Student Innovation', 'Software', 'MedTech / BioTech / HealthTech', 'AICTE', NULL),
('SIH26197', 'Student Innovation', 'Software', 'Agriculture, FoodTech & Rural Development', 'AICTE', NULL),
('SIH26198', 'Student Innovation', 'Software', 'Transportation & Logistics', 'AICTE', NULL),
('SIH26199', 'Student Innovation', 'Software', 'Fitness & Sports', 'AICTE', NULL),
('SIH26200', 'Student Innovation', 'Software', 'MedTech / BioTech / HealthTech', 'AICTE', NULL),
('SIH26201', 'Student Innovation', 'Software', 'Smart Resource Conservation', 'AICTE', NULL),
('SIH26202', 'Student Innovation', 'Software', 'Travel & Tourism', 'AICTE', NULL),
('SIH26203', 'Student Innovation', 'Software', 'Renewable / Sustainable Energy', 'AICTE', NULL),
('SIH26204', 'Student Innovation', 'Software', 'Miscellaneous', 'AICTE', NULL),
('SIH26205', 'Student Innovation', 'Software', 'Smart Education', 'AICTE', NULL),
('SIH26206', 'Student Innovation', 'Software', 'Disaster Management', 'AICTE', NULL),
('SIH26207', 'Student Innovation', 'Software', 'Travel & Tourism', 'AICTE', NULL),
('SIH26208', 'Student Innovation', 'Software', 'Heritage & Culture', 'AICTE', NULL),
('SIH26209', 'Student Innovation', 'Software', 'Space Technology', 'AICTE', NULL),
('SIH26210', 'Student Innovation', 'Hardware', 'Smart Resource Conservation', 'AICTE', NULL),
('SIH26211', 'Student Innovation', 'Hardware', 'Fitness & Sports', 'AICTE', NULL),
('SIH26212', 'Student Innovation', 'Hardware', 'Heritage & Culture', 'AICTE', NULL),
('SIH26213', 'Student Innovation', 'Hardware', 'MedTech / BioTech / HealthTech', 'AICTE', NULL),
('SIH26214', 'Student Innovation', 'Hardware', 'Agriculture, FoodTech & Rural Development', 'AICTE', NULL),
('SIH26215', 'Student Innovation', 'Hardware', 'Transportation & Logistics', 'AICTE', NULL),
('SIH26216', 'Student Innovation', 'Hardware', 'Fitness & Sports', 'AICTE', NULL),
('SIH26217', 'Student Innovation', 'Hardware', 'MedTech / BioTech / HealthTech', 'AICTE', NULL),
('SIH26218', 'Student Innovation', 'Hardware', 'Smart Resource Conservation', 'AICTE', NULL),
('SIH26219', 'Student Innovation', 'Hardware', 'Travel & Tourism', 'AICTE', NULL),
('SIH26220', 'Student Innovation', 'Hardware', 'Renewable / Sustainable Energy', 'AICTE', NULL),
('SIH26221', 'Student Innovation', 'Hardware', 'Miscellaneous', 'AICTE', NULL),
('SIH26222', 'Student Innovation', 'Hardware', 'Smart Education', 'AICTE', NULL),
('SIH26223', 'Student Innovation', 'Hardware', 'Disaster Management', 'AICTE', NULL),
('SIH26224', 'Student Innovation', 'Hardware', 'Travel & Tourism', 'AICTE', NULL),
('SIH26225', 'Student Innovation', 'Hardware', 'Heritage & Culture', 'AICTE', NULL),
('SIH26226', 'Student Innovation', 'Hardware', 'Space Technology', 'AICTE', NULL);